# -*- coding: utf-8 -*-
"""402100815.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZPIz59T0s0cckQ_IwJxQTe7iO1ziZTrW
"""

o = (input())
y = []
for x in range (10^32):
  x = input()
  if x != "end":
    y.append(int(x))
  else:
    break
a = o[0]
b = o[1]
import functools
import math
def find_lcm(a, b):
    return a * b // math.gcd(a, b)
lcm = functools.reduce(find_lcm, y)
def find_gcd(y):
    gcd = y[0]
    for num in y[1:]:
        gcd = math.gcd(gcd, num)
    return gcd
result = find_gcd(y)
if o == "sum":
  print(sum(y))
elif o == "average":
  print(round((sum(y)/len(y)), 2))
elif o == "min":
  print(min(y))
elif o == "max":
  print(max(y))
elif o == "lcd":
  print(lcm)
elif o == "gcd":
  print(result)
else:
  print("Invalid command")