# -*- coding: utf-8 -*-
"""prblm 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11oPfA5xEwpmqsc3DJRoqjyIK7HSKtx1T
"""

i = 0
j = 0
s = int(input())
a = []
b = []
for x in range(s):
    a.append('.')
for x in range(100):
    c = a.copy()
    b.append(c)
b[i][j]='*'
d = input()
while d != "END":
  if d == "L":
        if i-1>=0:
            i -= 1
        else:
            i = 0
  elif d =="R":
        if i < s-1:
            i += 1
        else:
            i = s-1
  elif d == "B":
        j += 1
  b[j][i]='*'
  d = input()
while True:
    if a in b:
        b.pop(b.index(a))
    else:
        break
for y in range(len(b)):
    for z in range(s):
        print(b[y][z],end=' ')
    print('\n')
if i != s-1:
    print("There's no way out!")