# -*- coding: utf-8 -*-
"""prblm 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oYlKrPgk5DAUv9N6eoxN-o0Jiq9RmGi3
"""

a = []
c = 0
def binbasen(n, b):
    result = ""
    while n > 0:
        f = n % b
        result = str(f) + result
        n //= b
    return result
while True:
    d = 0
    n, b = map(int, input().split())
    if int(n)+int(b)==-2:
        if c > 0:
            print('invalid base!')
            exit()
        elif c == 0:
            break
    if b < 2 or b >= 10:
        c +=1
    for i in range(1 ,n+1):
        if n % i==0:
            d += (n // i)
    a.append(binbasen(d, b))
e = 0
for i in range(len(a)):
    e += int(a[i])
print(e)