# -*- coding: utf-8 -*-
"""تمرین 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nYyWNwNNoWSbL3MMb0CfBXNvD-o-VA39
"""

n=int(input())
def printPascal(n):
    for line in range(1, n + 1):
        C=1
        for i in range(1, line + 1):
            print(C,end= " ")
            C= int(C*(line - i)/i)
        print("")
printPascal(n)