# -*- coding: utf-8 -*-
"""3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bTHrmvMCJg6DlqutZnc8mfq5cxldrcv9
"""

import re
a = input()
a = re.sub(r' +',' ',a.strip())
a = re.sub(r"\\n","\n",a)
z = list(a)
b = 0
finalres=[]
c = ""
for i in z:
    if i == '@':
        finalres.append('@')
        b += 1
    elif i =='#' and b>0:
        b -= 1
    else:
        finalres.append(i)
for item in finalres:
     c += item
print('Formatted Text: '+ c)