# -*- coding: utf-8 -*-
"""soal1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erRbUp1Z8q44tbH5u_RX4jWeq1wSdbqK
"""

a = str(input())
def string():
    b = a.split(' ')
    b.sort(key = lambda x: int(x[1:]))
    for i in b:
      print(i[0], end='')
string()