# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erRbUp1Z8q44tbH5u_RX4jWeq1wSdbqK
"""

x = int(input())
c = {"1"}
for a in range (x):
  a = input()
  for i in range (len(a)):
    if a[i] == "@":
      c.add(a[i+1:len(a)])
c.remove("1")
d = sorted(c)
for y in (d):
  print(y)