# -*- coding: utf-8 -*-
"""q3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qae81InDMn5k4x_eoTSzChiRhbxG9X5Y
"""

s1 = 0
s2 = 0
ts1 = []
ts2 = []
def dictionary(numbers):
    if len(numbers) != 3:
        raise ValueError("Invalid Command.")
    return {"A": numbers[0], "B": numbers[1], "C": numbers[2]}
def play(p1, p2, h1, h2, d, r):
    for i in range(r):
        card1, card2 = input().split()
        h1-= d1
        h2-= d2
        d1 = d[card1]
        d2 = d[card2]
        if d1 > d2:
            s1+= 1
        elif d2 > d1:
            s2+= 1
        ts1.append(s1)
        ts2.append(s2)
try:
    p1, p2 = input().split()
    h1, h2 = map(int, input().split())
    d = dictionary(list(map(int, input().split())))
    play(p1, p2, h1, h2, d, 3)
except Exception as e:
    print("Invalid Command.")