# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j2_Q92t8TUPZWkBFLHvu8l5iSOe8Hhl
"""

a = int(input())
b = int(input())
print (int((str(bin(a ^ b))).count('1')))