# -*- coding: utf-8 -*-
"""تمرین 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nYyWNwNNoWSbL3MMb0CfBXNvD-o-VA39
"""

a = bin(int(input()))[2:]
b = bin(int(input()))[2:]
e = int(input())
c = "0" * (32-(len(a)))
d = "0" * (32-(len(b)))
m = d + b + c + a
for i in range (e):
    x = int(input())
    if int(m[-x-1]) == 1:
      print("yes")
    else:
      print("no")