# -*- coding: utf-8 -*-
"""تمرین 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hgaInI1KdfLEauB8vV2SOy4enoddbdvi
"""

def Add(x , y):
  while (y != 0):
    c = x & y
    x = x ^ y
    y = c << 1
  return x
a = int(input())
b = int(input())
d = int(input())
print (Add(a , b))
if Add(a , b) == d:
  print ("YES")
else: print("NO")